name = "Custom Keyboards"
version = "0.0.1"
link = "https://github.com/TheDgtl/crankshaft-custom-keyboards"
source = "https://github.com/TheDgtl/crankshaft-custom-keyboards"
min-crankshaft-version = "0.2.2"

[author]
name = "DrakiaXYZ"
link = "https://github.com/TheDgtl/"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
	quick-access = false

[store]
description = """
This plugin allows you to load custom keyboards directly in the Settings 
menu.

Keyboards are loaded from the ~/homebrew/keyboards/ folder, and consist
of a simple JSON file, and CSS file, organised into folders.

For example, an RGB keyboard maybe live in the following files:
~/homebrew/keyboards/rgb/keyboard.json
~/homebrew/keyboards/rgb/keyboard.css

This plugin is only compatible with the gamepad/Steam Deck UI.
"""
